travis:
  secure:
    BINSTAR_TOKEN: djbOWL1E3fvbR98cVKaiZQrpxzULHwa+muEkdNCM64cJrHhWMqxjtM7hqPnmWn6jIxtrBM5umsrIrbdRFbLTpVKKunjmX87ptjCH6i9KRho1PntM6+dKWeNYPp5gRG6A2DcQ+/iYXkhQBTtXu1dqzGcw3z7JKoqmz4x9nzpLDvP9k+W1frpMElzzn/mfHEvFBBwf3UO71359zhiK52J85n4igbKgZsEQyP6Rc4MZq3LZLFbqw7grWeQhsopaCWlzcX0Y1DzqcmjVm/Ab9G1E9zltJucEBhTr/SW3l53e/yFzWNXTM7115iTCNBjuiVTL4udOLviSeK58IhjK8tXcM/lmBiIs0KtmhnzTaQr+qjLzjkL/FCU+A4+NFNego7lSqp3YDXRNo16HPuKEe8WKM0kfNst5TxeNrTelW66/wm/Xz0cO9wJH91FaH0hEWT4em28lXl1j1kTgDak+gD/HGhecjUdc/S1o63ScEBZTjPmTZoEnIupel9fK9ro0/K58ICiXWLqH4DJAEZyN8wYNlN+yw9+1jku5G0yR5UuwoteZt/Frysph6LUcvCEevYVl3ibgddmHfujVMtW7nGs0qKNne954ekdOA8xJfAaV+qKuOe+D+fcPDHhezTpLOEmUMUWtN7XICdM4urVSTZfMv1J/1O++kxnh6saXH60RryE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
