appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: wpJahVpBc2DTJcAuXARiBzzK+fdPSC4BKlhONF8XepkJgODQKKPuQyF8XznqPLNfzOREz8KzLP2aK0aP2Iop2SstZ2RjffEILxJGvwYRWvuD7ACjo2+sNYDoEEbrowdEVlHZbvcnnGMauICd8jAaoxOW1sGXSoG0mTLfLhJuiovsngjbUmvqrAD+awYkal+UbhrU5e1NJjreY10UrclCmhomSHRW7QBaE+tIUjz9Jdd0q6wSgnoOj1dy2+7y2yYiUADg/fw6H583fqpScGFNzNMt5nX+GJeDDDTZBjx9fSRNXCF2c9Kc1ZKyJTriQHPA9rVhfNAwc5UXOnOZIiKwjxueyYJ5SVorrCw6eL8Qvo3w5yYvgWVMm9PtkvqigKJ32d1cmRJy/ss2y14GLvTO2SSZ2Speq4kKEzXogMzOSSu6UMfygZzmOxQccGYy/Xv+cBYhmopI+g+T8hRruFn5V4IeGIAA5WliFun15n+KaPsE1o69tQftUDTYvcqPDwel0PivkVsqQdsw1ngKY+Pj+ttKH6wR/ngbRuzpE26UeFeuXUbdEI+thzlq4G2MgcWPVKBQpmeNCjs56aryG4vamWj/kwehR/F3Kb1BDRSbLzi7MDuZtWE70TV0s20FstAc8bPqL/pwdcqqYNPGaPiTBlBiYlSy5NNRbl1cl8hdVr0=}
provider:
  win: azure
