travis:
  secure:
    BINSTAR_TOKEN: u22AdPD5+iOjgMac/vZD3BEhd3oz9dJw8Wt/g+lp3vYyCBaVl3H7m8RZtLBPSnXsZrrRH2XlDO76ucvCAlrH05EXgKnYmyK36CmsawbjOYxhPLfp+UMHMbAjuBfThB1D4boXop1kfDhah4AZhzMO4azvIeirZ0b8n1nZhsZGe8mVrfUuzH7XuT/jq7WPsSbJRpQ2i5Bj1ak5MgDLZYBMGVwucRVPX1yASfUE2JDOSWDKgyQ7Gu2gboS0zYwrKMRALupn0L9D0iCfEq3iiwNDYC48/djDzutbIrHCVr0FQyey5nRLWu1HD9T6UiDc+T+3f4BpZS2EgxfRDUIu/unAZR0u59D0AxfQq8Vd2iPv/ufMrXpd67DpKH3EQY5PsPzS+Tar0TL9Ks9YgM6Czf21VZVENhLX9aOJb1QeFHqOd9qjTfgymNOnIeXPpST9cVF/U83MD7g6a36W+3KMPddYZUGp4e4+59t6R4igEUVcE9nV+XHRyUXpNir9Px/iVWUOCs+Abg537WEe2DVcwyOuhomENCx3wyhc/IEk2jqmnz/DNdGdmZNtKxgFWtnQPg2EEXnkkWonZASt/LjgbAoP4mB4FhrTM3fSJkRW6Yr3FwTiM+E1+vB57167L0h5OMhnOekp0yY9jIqnI0yNZIudmgVJTi91GeRolMrxFHRMGao=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
